#!/bin/zsh -e

# Shell script version of `nom-cp` alias
# Typically used with `sync-rsync` extension to VSCode.

mydir=${0:a:h}

source $mydir/aliases

# fish out file name from what VSCode 'sync-rsync' package sends us -- should be 2nd to last arg
# switch dirs to make aliases work
FILE=$(echo "$@" |rev |tr -s ' ' |cut -f2 -d' ' |rev)
DIR=$(dirname "$FILE")
cd "$DIR"

nom-cp "$@"
